# Water conflicts in the Colorado River Basin 

### Archive exploration 
1. Where was the data collected from??
 The data was collected via two methods. The first method was researchers observing meetings at water control boards and organizations in the Colorado River Basin. This data was analyzed for the ,major themes discussed at the meetings. The second method of data collection was looking at the archives of water-related events in the basin from newspapers.
2. During what time frame were the observations in the dataset collected?
The data is from 2005-2021.
3. What was the author’s perceived value of this dataset?
 The author believes this dataset is useful background information for the USGS which producing new water availability assessment reports.

In [1]:
# Import libraries
import pandas as pd

# Read in data
df = pd.read_csv( 'data/Colorado-River-Basin-Water-Conflict-Table.csv')

In [58]:
# Shows how many nas per column
df.isna().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [2]:
# Show all column names in the data frame 
df.columns

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='object')

In [3]:
# View first 5 rows of dataframe
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [4]:
# View columns and how many non-null value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    object
 2   Newspaper                                     268 non-null    object
 3   Article Title                                 268 non-null    object
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    object
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    object
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    object
 12  Crisis Present                                254 non-null    object
 13  Basin                                         250 non-null    object
 14  HUC6                                          110 non-null    object
 15  HUC2                                          250 non-null    object
 16  Place                                         254 non-null    object
 17  County                                        8 non-null      object
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    object
 20  State FIPS                                    178 non-null    object
 21  Urban or Rural                                254 non-null    object
 22  Issue Type                                    255 non-null    object
 23  Event Summary                                 256 non-null    object
 24  Stakeholders                                  255 non-null    object
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    object
 27  Related Observation Themes                    86 non-null     object
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(21)
memory usage: 100.6+ KB

In [5]:
# View number of unique values for each column
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [7]:
df.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

## 6. Examining state codes

Look at unique state codes where water conflicts are occuring

In [11]:
df['State'].unique()

array(['CO', 'UT', nan, 'AZ', 'OH; UT', 'AZ; CO; NM; UT', 'CA', 'AZ; UT',
       'AZ; NV', 'CO; UT; WY; NM', 'AZ; CA', 'UT; AZ', 'CO; WY', 'NV; AZ',
       'CO; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'AZ; CA; NV', 'NV', 'NM',
       'UT; CO; WY', 'CA; NV; AZ', 'AZ; NM', 'WY; UT; CO', 'TX'],
      dtype=object)

In [12]:
df['Conflict Present'].unique()

array(['Y', 'N', nan], dtype=object)

In [15]:
# Filter for water conflict
water_con = df[df['Conflict Present']== 'Y']

water_con

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,...,1,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,...,15,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,258,USGS301-350.docx,The Arizona Republic (Phoenix),"At Canyon, water battle rages anew",False,22-Feb-09,2009.0,1,NaN,1.0,...,2,0,0,0,4,0,0,0,0,0
258,259,USGS301-350.docx,The Salt Lake Tribune,Alder: A new set of negotiations need for The ...,False,29-Aug-08,2008.0,8,NaN,8.0,...,4,0,0,0,2,0,0,0,2,0
260,261,USGS301-350.docx,Farmington Daily Times (New Mexico),Experts predict low San Juan County river flow...,False,11-Apr-15,2015.0,4,NaN,4.0,...,7,0,0,0,0,0,0,0,0,0
262,263,USGS301-350.docx,Associated Press State & Local,Officials: Arizona will miss US deadline for k...,False,20-Feb-19,2019.0,2/19/2019,19.0,2.0,...,6,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,...,2,0,0,0,0,0,0,0,0,0

# Unique values for states with conlicts

Assuming that the semi-colon means that are states in that block were affected by conflict events.

In [17]:
# Looking at the unique values for states
water_con['State'].unique()

array(['CO', nan, 'AZ', 'OH; UT', 'UT', 'CA', 'AZ; NV', 'CO; UT; WY; NM',
       'AZ; CA', 'AZ; UT', 'NV; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'NV',
       'NM', 'UT; CO; WY', 'AZ; NM', 'WY; UT; CO', 'CO; AZ'], dtype=object)

In [47]:
# Split the state codes with semi-colons
# str.strip() removes any white space from the 
# NOTE: ADD A SPACE IF THERE IS A SPACE IN THE SPLIT TO ENSURE THAT THE STRING MATCHES THE OTHER OPTIONS
water_con_st = water_con['State'].str.split("; ", expand = True).stack().str.strip()

# Convert the stacked data frame to a series
water_con_st_ser = pd.Series(water_con_st.unique())
water_con_st_ser

0    CO
1    AZ
2    OH
3    UT
4    CA
5    NV
6    WY
7    NM
dtype: object

In [38]:
# Looking at the unique values for states 
states_w_con = water_con_st.unique()
states_w_con

array(['CO', 'AZ', 'OH', 'UT', 'CA', 'NV', 'WY', 'NM'], dtype=object)

# 9. Finding unique state codes

In [41]:
# Look at dataframe that already only looks at water conflicts
water_con

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,...,1,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,...,15,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,258,USGS301-350.docx,The Arizona Republic (Phoenix),"At Canyon, water battle rages anew",False,22-Feb-09,2009.0,1,NaN,1.0,...,2,0,0,0,4,0,0,0,0,0
258,259,USGS301-350.docx,The Salt Lake Tribune,Alder: A new set of negotiations need for The ...,False,29-Aug-08,2008.0,8,NaN,8.0,...,4,0,0,0,2,0,0,0,2,0
260,261,USGS301-350.docx,Farmington Daily Times (New Mexico),Experts predict low San Juan County river flow...,False,11-Apr-15,2015.0,4,NaN,4.0,...,7,0,0,0,0,0,0,0,0,0
262,263,USGS301-350.docx,Associated Press State & Local,Officials: Arizona will miss US deadline for k...,False,20-Feb-19,2019.0,2/19/2019,19.0,2.0,...,6,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,...,2,0,0,0,0,0,0,0,0,0

How many articles mention each state?

In [45]:

df['State'].valuecount

In [57]:
?df.str.strip

Object `df.str.strip` not found.